[package]
name = "hdk_unit_testing"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdk = "0.0.115"

[features]
default = ["mock"]
mock = ["hdk/mock", "hdk/test_utils"]